### ISSUE TITLE
Провести проверку на большом файле

### ISSUE THREAD

**Issue by alexkoss** [vlad-1308/DisjointSets#1]
Файл: https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z

В ответе должно быть количество групп и время выполнения.

**Comment by alexkoss** [comment]
Буду ждать до понедельника, потом потеряет актуальность.

**Comment by vlad-1308** [comment]
105036 групп всего.
105036 групп с 2 и более строками.
14.582 секунд.

Прошу прощения, с рабочего компа вчера не мог этого сделать.
